AppBundle\Entity\Users:
    type: entity
    table: users
    indexes:
        role:
            columns:
                - role
        city:
            columns:
                - city
        galery:
            columns:
                - galery
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        profilpicture:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: profilPicture
        firstname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        birthday:
            type: date
            nullable: true
        phone:
            type: integer
            nullable: true
            options:
                unsigned: false
        bio:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        adress:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        city:
            type: integer
            nullable: false
            options:
                unsigned: false
        connected:
            type: boolean
            nullable: true
        lastconnect:
            type: date
            nullable: true
        nbrexpo:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: nbrExpo
        galery:
            type: integer
            nullable: false
            options:
                unsigned: true
    manyToOne:
        role:
            targetEntity: Roles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
